title: Junha Roh
logo: /assets/img/profile.jpg
description: A Ph.D. Student<br />Computer Science and Engineering<br />Paul G. Allen School<br />University of Washington<br />[<a href="assets/cv.pdf">cv</a>][<a href="mailto:rohjunha@cs.washington.edu">email</a>]
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
